# Generated by Django 5.2 on 2025-05-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(verbose_name="nome")),
                ("price", models.FloatField(verbose_name="preço")),
                (
                    "unity_type",
                    models.IntegerField(
                        choices=[(0, "unidade"), (1, "cento"), (2, "kg")],
                        default=0,
                        verbose_name="tipo de unidade",
                    ),
                ),
                (
                    "minimum",
                    models.FloatField(default=0, verbose_name="quantidade mínima"),
                ),
                ("avaliable", models.BooleanField(verbose_name="disponibilidade")),
            ],
            options={
                "verbose_name": "Produto",
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(verbose_name="nome")),
                (
                    "products",
                    models.ManyToManyField(
                        default=None, related_name="menus", to="cardapio.product"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cardápio",
            },
        ),
    ]
