# Generated by Django 5.2 on 2025-05-12 23:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cardapio", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="unity_type",
            new_name="unit_type",
        ),
    ]
