# Generated by Django 5.2 on 2025-05-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardapio", "0002_rename_unity_type_product_unit_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.CharField(
                default="https://www.thefuzzyduck.co.uk/wp-content/uploads/2024/05/image-coming-soon-placeholder-01-660x660.png",
                verbose_name="url da imagem",
            ),
        ),
    ]
