# Generated by Django 5.2.1 on 2025-05-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardapio", "0004_product_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="Combo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(verbose_name="nome")),
                (
                    "image",
                    models.CharField(
                        default="https://www.thefuzzyduck.co.uk/wp-content/uploads/2024/05/image-coming-soon-placeholder-01-660x660.png",
                        verbose_name="url da imagem",
                    ),
                ),
                ("details", models.CharField(verbose_name="detalhes")),
                ("price", models.FloatField(verbose_name="preço")),
                ("avaliable", models.BooleanField(verbose_name="disponibilidade")),
            ],
            options={
                "verbose_name": "Combo",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="minimum",
            field=models.FloatField(default=1, verbose_name="quantidade mínima"),
        ),
        migrations.AddField(
            model_name="menu",
            name="combos",
            field=models.ManyToManyField(
                default=None, related_name="menus", to="cardapio.combo"
            ),
        ),
    ]
