# Generated by Django 5.2.1 on 2025-05-28 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardapio", "0005_combo_alter_product_minimum_menu_combos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="combo",
            name="avaliable",
            field=models.BooleanField(verbose_name="disponível"),
        ),
        migrations.AlterField(
            model_name="product",
            name="avaliable",
            field=models.BooleanField(verbose_name="disponível"),
        ),
        migrations.CreateModel(
            name="ComboCombo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("optional", models.BooleanField(default=False)),
                (
                    "combo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="included_product",
                        to="cardapio.combo",
                    ),
                ),
                (
                    "included_combo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cardapio.combo"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="combo",
            name="included_combos",
            field=models.ManyToManyField(
                blank=True,
                through="cardapio.ComboCombo",
                through_fields=("combo", "included_combo"),
                to="cardapio.combo",
                verbose_name="Combos Inclusos",
            ),
        ),
        migrations.CreateModel(
            name="ComboProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("optional", models.BooleanField(default=False)),
                (
                    "combo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="included_combo",
                        to="cardapio.combo",
                    ),
                ),
                (
                    "included_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cardapio.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="combo",
            name="included_products",
            field=models.ManyToManyField(
                blank=True,
                through="cardapio.ComboProduct",
                through_fields=("combo", "included_product"),
                to="cardapio.product",
                verbose_name="Produtos Inclusos",
            ),
        ),
    ]
