# Generated by Django 5.2.1 on 2025-05-28 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardapio", "0006_alter_combo_avaliable_alter_product_avaliable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="combo",
            name="maximum_optionals_quantity",
            field=models.IntegerField(
                default=255, verbose_name="quantidade máxima de opcionais"
            ),
        ),
        migrations.AddField(
            model_name="combo",
            name="minimum_optionals_quantity",
            field=models.IntegerField(
                default=1, verbose_name="quantidade mínima de opcionais"
            ),
        ),
        migrations.AlterField(
            model_name="combocombo",
            name="included_combo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cardapio.combo",
                verbose_name="combo incluso",
            ),
        ),
        migrations.AlterField(
            model_name="combocombo",
            name="optional",
            field=models.BooleanField(default=False, verbose_name="opcional"),
        ),
        migrations.AlterField(
            model_name="comboproduct",
            name="included_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cardapio.product",
                verbose_name="produto incluso",
            ),
        ),
        migrations.AlterField(
            model_name="comboproduct",
            name="optional",
            field=models.BooleanField(default=False, verbose_name="opcional"),
        ),
    ]
