# Generated by Django 5.2.1 on 2025-06-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardapio", "0008_alter_combo_avaliable_alter_menu_combos_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="combo",
            name="image",
            field=models.CharField(
                default="/static/cardapio/img/coming-soon-placeholder.png",
                verbose_name="url da imagem",
            ),
        ),
    ]
