# Generated by Django 5.2.1 on 2025-06-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardapio", "0009_alter_combo_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="combo",
            name="maximum_optionals_quantity",
        ),
        migrations.RemoveField(
            model_name="combo",
            name="minimum_optionals_quantity",
        ),
        migrations.RemoveField(
            model_name="combocombo",
            name="optional",
        ),
        migrations.RemoveField(
            model_name="comboproduct",
            name="optional",
        ),
        migrations.AddField(
            model_name="combocombo",
            name="quantity",
            field=models.IntegerField(default=0, verbose_name="quantidade"),
        ),
        migrations.AddField(
            model_name="comboproduct",
            name="quantity",
            field=models.IntegerField(default=0, verbose_name="quantidade"),
        ),
    ]
