# Generated by Django 5.2.1 on 2025-06-24 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardapio", "0010_remove_combo_maximum_optionals_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="combocombo",
            name="combo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="included_combo",
                to="cardapio.combo",
            ),
        ),
        migrations.AlterField(
            model_name="comboproduct",
            name="combo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="included_product",
                to="cardapio.combo",
            ),
        ),
    ]
