# Generated by Django 5.2.1 on 2025-06-25 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardapio", "0011_alter_combocombo_combo_alter_comboproduct_combo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComboChoices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(verbose_name="título")),
                ("description", models.TextField(verbose_name="descrição")),
                (
                    "minimun_choices",
                    models.IntegerField(
                        default=0, verbose_name="quantidade mínima de escolhas"
                    ),
                ),
                (
                    "maximun_choices",
                    models.IntegerField(
                        default=255, verbose_name="quantidade máxima de escolhas"
                    ),
                ),
            ],
            options={
                "verbose_name": "Campo Personalizável do Combo",
            },
        ),
        migrations.AddField(
            model_name="combo",
            name="included_choices",
            field=models.ManyToManyField(to="cardapio.combochoices"),
        ),
        migrations.CreateModel(
            name="ComboChoicesProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selected", models.BooleanField(verbose_name="selecionado")),
                (
                    "combo_choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="included_product",
                        to="cardapio.combochoices",
                    ),
                ),
                (
                    "included_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cardapio.product",
                        verbose_name="produto incluso",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="combochoices",
            name="included_products",
            field=models.ManyToManyField(
                blank=True,
                through="cardapio.ComboChoicesProduct",
                through_fields=("combo_choice", "included_product"),
                to="cardapio.product",
                verbose_name="Produtos Inclusos",
            ),
        ),
    ]
