# Generated by Django 5.2.1 on 2025-06-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardapio", "0012_combochoices_combo_included_choices_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="combochoices",
            options={"verbose_name": "Campo Personalizável de Combo"},
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(
                default="descrição genérica", verbose_name="descrição"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="combo",
            name="included_choices",
            field=models.ManyToManyField(
                to="cardapio.combochoices", verbose_name="Campos Personalizáveis"
            ),
        ),
    ]
